// Datos de ejemplo: se usan cuando Supabase no está configurado.
// Son los mismos que carga supabase/seed.sql.
import type { NewsArticle, Player, Tournament } from "@/types/models";

const created_at = "2026-09-01T12:00:00Z";

export const demoPlayers: Player[] = [
  {
    id: 1,
    slug: "martin-gomez",
    first_name: "Martín",
    last_name: "Gómez",
    photo_url: null,
    city: "América",
    club: "Complejo El Remate",
    category: "1ra",
    gender: "masculino",
    side: "drive",
    ranking_points: 2480,
    matches_played: 38,
    matches_won: 29,
    titles: 4,
    bio: "Número uno del ranking regional. Drive agresivo, juega en pareja con Nicolás Ibarra desde 2024.",
    created_at,
  },
  {
    id: 2,
    slug: "lucas-ferreyra",
    first_name: "Lucas",
    last_name: "Ferreyra",
    photo_url: null,
    city: "Trenque Lauquen",
    club: "Pádel Norte",
    category: "1ra",
    gender: "masculino",
    side: "reves",
    ranking_points: 2315,
    matches_played: 35,
    matches_won: 25,
    titles: 3,
    bio: "Especialista en la bandeja y la víbora. Campeón del Clásico del Oeste 2026.",
    created_at,
  },
  {
    id: 3,
    slug: "tomas-aguirre",
    first_name: "Tomás",
    last_name: "Aguirre",
    photo_url: null,
    city: "Pehuajó",
    club: "Bandeja Club",
    category: "2da",
    gender: "masculino",
    side: "drive",
    ranking_points: 2140,
    matches_played: 33,
    matches_won: 22,
    titles: 2,
    bio: "La revelación de la temporada: subió de 3ra a 2da en un año.",
    created_at,
  },
  {
    id: 4,
    slug: "nicolas-ibarra",
    first_name: "Nicolás",
    last_name: "Ibarra",
    photo_url: null,
    city: "América",
    club: "Complejo El Remate",
    category: "2da",
    gender: "masculino",
    side: "reves",
    ranking_points: 1985,
    matches_played: 30,
    matches_won: 19,
    titles: 1,
    bio: "Revés sólido y mucha lectura de juego. Compañero de Martín Gómez.",
    created_at,
  },
  {
    id: 5,
    slug: "franco-medina",
    first_name: "Franco",
    last_name: "Medina",
    photo_url: null,
    city: "General Villegas",
    club: "La Blindex",
    category: "3ra",
    gender: "masculino",
    side: "drive",
    ranking_points: 1720,
    matches_played: 28,
    matches_won: 16,
    titles: 1,
    bio: "Fijo en todos los torneos del circuito desde hace tres temporadas.",
    created_at,
  },
  {
    id: 6,
    slug: "joaquin-sosa",
    first_name: "Joaquín",
    last_name: "Sosa",
    photo_url: null,
    city: "Salliqueló",
    club: "Pádel Oeste",
    category: "3ra",
    gender: "masculino",
    side: "reves",
    ranking_points: 1590,
    matches_played: 26,
    matches_won: 14,
    titles: 0,
    bio: "Debutó en el circuito en 2025 y ya pelea los primeros puestos de 3ra.",
    created_at,
  },
  {
    id: 7,
    slug: "camila-rodriguez",
    first_name: "Camila",
    last_name: "Rodríguez",
    photo_url: null,
    city: "América",
    club: "Bandeja Club",
    category: "1ra",
    gender: "femenino",
    side: "reves",
    ranking_points: 2390,
    matches_played: 36,
    matches_won: 28,
    titles: 5,
    bio: "Líder del ranking femenino con cinco títulos regionales.",
    created_at,
  },
  {
    id: 8,
    slug: "sofia-benitez",
    first_name: "Sofía",
    last_name: "Benítez",
    photo_url: null,
    city: "Trenque Lauquen",
    club: "Pádel Norte",
    category: "1ra",
    gender: "femenino",
    side: "drive",
    ranking_points: 2270,
    matches_played: 34,
    matches_won: 24,
    titles: 3,
    bio: "Drive potente y gran definición por arriba. Finalista de la Copa Aniversario.",
    created_at,
  },
  {
    id: 9,
    slug: "valentina-castro",
    first_name: "Valentina",
    last_name: "Castro",
    photo_url: null,
    city: "Pehuajó",
    club: "La Blindex",
    category: "2da",
    gender: "femenino",
    side: "reves",
    ranking_points: 2050,
    matches_played: 31,
    matches_won: 21,
    titles: 2,
    bio: "Campeona de la Copa Aniversario 2026 junto a Florencia Molina.",
    created_at,
  },
  {
    id: 10,
    slug: "florencia-molina",
    first_name: "Florencia",
    last_name: "Molina",
    photo_url: null,
    city: "Carlos Tejedor",
    club: "Pádel Oeste",
    category: "2da",
    gender: "femenino",
    side: "drive",
    ranking_points: 1890,
    matches_played: 29,
    matches_won: 18,
    titles: 1,
    bio: "Campeona de la Copa Aniversario 2026 y referente del pádel en Carlos Tejedor.",
    created_at,
  },
  {
    id: 11,
    slug: "julieta-paz",
    first_name: "Julieta",
    last_name: "Paz",
    photo_url: null,
    city: "América",
    club: "Complejo El Remate",
    category: "3ra",
    gender: "femenino",
    side: "reves",
    ranking_points: 1705,
    matches_played: 27,
    matches_won: 15,
    titles: 1,
    bio: "Juega en América desde chica y es una de las promesas del circuito.",
    created_at,
  },
  {
    id: 12,
    slug: "agustina-rios",
    first_name: "Agustina",
    last_name: "Ríos",
    photo_url: null,
    city: "General Villegas",
    club: "Bandeja Club",
    category: "3ra",
    gender: "femenino",
    side: "drive",
    ranking_points: 1560,
    matches_played: 25,
    matches_won: 13,
    titles: 0,
    bio: "Constancia pura: no se perdió ningún torneo de la temporada.",
    created_at,
  },
];

export const demoTournaments: Tournament[] = [
  {
    id: 1,
    slug: "abierto-de-primavera-2026",
    name: "Abierto de Primavera",
    description:
      "El torneo que abre la temporada de primavera en América. Tres días de pádel en las canchas del Complejo El Remate, con cuadros de 1ra y 2da masculino y puntos para el ranking regional.\n\nLas parejas se arman libremente. Cupo limitado a 24 parejas por categoría.",
    city: "América",
    venue: "Complejo El Remate",
    starts_on: "2026-10-09",
    ends_on: "2026-10-11",
    category: "1ra y 2da",
    gender: "masculino",
    status: "inscripciones",
    prize: "$1.500.000 en premios",
    champions: null,
    address: "América, Rivadavia, Buenos Aires",
    maps_url: null,
    capacity: 24,
    registration_opens_on: null,
    cover_url: null,
    created_at,
  },
  {
    id: 2,
    slug: "copa-ciudad-de-trenque-lauquen-2026",
    name: "Copa Ciudad de Trenque Lauquen",
    description:
      "Torneo femenino de 3ra a 5ta categoría con fase de grupos y playoffs. Ideal para jugadoras que quieren sumar sus primeros puntos en el ranking.\n\nIncluye cena de camaradería el sábado a la noche.",
    city: "Trenque Lauquen",
    venue: "Pádel Norte",
    starts_on: "2026-10-23",
    ends_on: "2026-10-25",
    category: "3ra a 5ta",
    gender: "femenino",
    status: "inscripciones",
    prize: "Trofeos y $800.000 en premios",
    champions: null,
    address: "Trenque Lauquen, Buenos Aires",
    maps_url: null,
    capacity: 16,
    registration_opens_on: null,
    cover_url: null,
    created_at,
  },
  {
    id: 3,
    slug: "torneo-mixto-nocturno-2026",
    name: "Torneo Mixto Nocturno",
    description:
      "Partidos de 20 a 2 h en la nueva cancha panorámica de Bandeja Club. Parejas mixtas, categoría suma 13.\n\nLas inscripciones abren el 20 de octubre.",
    city: "Pehuajó",
    venue: "Bandeja Club",
    starts_on: "2026-11-13",
    ends_on: "2026-11-14",
    category: "Suma 13",
    gender: "mixto",
    status: "proximo",
    prize: null,
    champions: null,
    address: "Pehuajó, Buenos Aires",
    maps_url: null,
    capacity: 20,
    registration_opens_on: "2026-10-20",
    cover_url: null,
    created_at,
  },
  {
    id: 4,
    slug: "master-de-fin-de-ano-2026",
    name: "Master de Fin de Año",
    description:
      "Los 8 mejores jugadores del ranking masculino se enfrentan en el cierre de la temporada. Formato round robin y final el domingo.\n\nEntrada libre y gratuita para el público.",
    city: "América",
    venue: "Complejo El Remate",
    starts_on: "2026-12-11",
    ends_on: "2026-12-13",
    category: "Top 8 del ranking",
    gender: "masculino",
    status: "proximo",
    prize: "$3.000.000 en premios",
    champions: null,
    address: "América, Rivadavia, Buenos Aires",
    maps_url: null,
    capacity: null,
    registration_opens_on: null,
    cover_url: null,
    created_at,
  },
  {
    id: 5,
    slug: "clasico-del-oeste-2026",
    name: "Clásico del Oeste",
    description:
      "El clásico de mitad de año, con parejas de toda la región en Carlos Tejedor.",
    city: "Carlos Tejedor",
    venue: "Polideportivo Municipal",
    starts_on: "2026-06-12",
    ends_on: "2026-06-14",
    category: "1ra",
    gender: "masculino",
    status: "finalizado",
    prize: null,
    champions: "Ferreyra / Aguirre",
    address: "Carlos Tejedor, Buenos Aires",
    maps_url: null,
    capacity: null,
    registration_opens_on: null,
    cover_url: null,
    created_at,
  },
  {
    id: 6,
    slug: "invierno-padel-tour-2026",
    name: "Invierno Pádel Tour",
    description:
      "Fecha única del tour de invierno, con 20 parejas de 1ra categoría de toda la zona.",
    city: "General Villegas",
    venue: "La Blindex",
    starts_on: "2026-07-17",
    ends_on: "2026-07-19",
    category: "1ra",
    gender: "masculino",
    status: "finalizado",
    prize: null,
    champions: "Gómez / Ibarra",
    address: "General Villegas, Buenos Aires",
    maps_url: null,
    capacity: null,
    registration_opens_on: null,
    cover_url: null,
    created_at,
  },
  {
    id: 7,
    slug: "copa-aniversario-padel-oeste-2026",
    name: "Copa Aniversario Pádel Oeste",
    description:
      "Torneo femenino por el aniversario de Pádel Oeste, con cuadros de 2da y 3ra.",
    city: "Salliqueló",
    venue: "Pádel Oeste",
    starts_on: "2026-08-14",
    ends_on: "2026-08-16",
    category: "2da y 3ra",
    gender: "femenino",
    status: "finalizado",
    prize: null,
    champions: "Castro / Molina",
    address: "Salliqueló, Buenos Aires",
    maps_url: null,
    capacity: null,
    registration_opens_on: null,
    cover_url: null,
    created_at,
  },
];

/** Lugares ocupados de ejemplo (en Supabase salen de las inscripciones). */
export const demoSpots: Record<number, number> = { 1: 18, 2: 7 };

const author = "Redacción PaddleAmerica";

export const demoNews: NewsArticle[] = [
  {
    id: 1,
    slug: "inscripciones-abierto-de-primavera",
    title: "Abrieron las inscripciones para el Abierto de Primavera",
    excerpt:
      "Del 9 al 11 de octubre en el Complejo El Remate de América, con cuadros de 1ra y 2da masculino y $1.500.000 en premios.",
    body: "Ya están abiertas las inscripciones para el Abierto de Primavera, el torneo que da inicio a la segunda mitad de la temporada del circuito regional. Se jugará del 9 al 11 de octubre en las canchas del Complejo El Remate, en América.\n\nHabrá cuadros de 1ra y 2da categoría masculina, con un cupo de 24 parejas por categoría. El torneo reparte $1.500.000 en premios y suma puntos para el ranking regional.\n\nPara anotarte, creá tu cuenta en el sitio y completá la inscripción desde la página del torneo.",
    tag: "Torneos",
    author,
    cover_url: null,
    is_published: true,
    published_at: "2026-09-10T15:00:00Z",
    created_at,
  },
  {
    id: 2,
    slug: "bandeja-club-estrena-cancha-panoramica",
    title: "Bandeja Club estrena cancha panorámica en Pehuajó",
    excerpt:
      "Es la primera cancha 100% de vidrio de la zona y va a ser sede del Torneo Mixto Nocturno.",
    body: "Bandeja Club inauguró su nueva cancha panorámica, la primera de la región con paredes completamente de vidrio y sin columnas en los laterales.\n\nLa cancha cuenta con iluminación LED y gradas para 120 personas, y será la sede del Torneo Mixto Nocturno de noviembre.",
    tag: "Clubes",
    author,
    cover_url: null,
    is_published: true,
    published_at: "2026-09-05T13:00:00Z",
    created_at,
  },
  {
    id: 3,
    slug: "ranking-despues-de-agosto",
    title: "Así quedó el ranking regional después de agosto",
    excerpt:
      "Martín Gómez y Camila Rodríguez siguen al frente. Tomás Aguirre, la gran sorpresa del mes.",
    body: "Con los puntos de la Copa Aniversario ya sumados, se actualizó el ranking regional. Martín Gómez sigue siendo el número uno en masculino y Camila Rodríguez lidera el femenino por segundo mes consecutivo.\n\nEl gran salto lo dio Tomás Aguirre, que tras ganar el Clásico del Oeste junto a Lucas Ferreyra ya es tercero en el ranking masculino.\n\nEl próximo movimiento llegará después del Abierto de Primavera, en octubre.",
    tag: "Ranking",
    author,
    cover_url: null,
    is_published: true,
    published_at: "2026-09-01T12:00:00Z",
    created_at,
  },
  {
    id: 4,
    slug: "castro-molina-campeonas-copa-aniversario",
    title: "Castro y Molina, campeonas de la Copa Aniversario",
    excerpt:
      "Vencieron en la final a Rodríguez y Benítez en un partido que se definió en el tercer set.",
    body: "Valentina Castro y Florencia Molina se quedaron con la Copa Aniversario de Pádel Oeste tras vencer en la final a Camila Rodríguez y Sofía Benítez por 6-4, 3-6 y 7-5.\n\nFue el primer título de la temporada para la pareja, que venía de perder dos semifinales seguidas. Con este resultado, ambas suben posiciones en el ranking femenino.",
    tag: "Torneos",
    author,
    cover_url: null,
    is_published: true,
    published_at: "2026-08-17T10:00:00Z",
    created_at,
  },
  {
    id: 5,
    slug: "gomez-ibarra-campeones-invierno-padel-tour",
    title: "Gómez e Ibarra ganaron el Invierno Pádel Tour",
    excerpt:
      "La pareja de América no perdió ningún set en todo el torneo disputado en General Villegas.",
    body: "Martín Gómez y Nicolás Ibarra fueron los campeones del Invierno Pádel Tour, que reunió a 20 parejas de 1ra categoría en las canchas de La Blindex, en General Villegas.\n\nEn la final superaron a Lucas Ferreyra y Tomás Aguirre por 6-3 y 6-2, cerrando un torneo en el que no cedieron ningún set.",
    tag: "Torneos",
    author,
    cover_url: null,
    is_published: true,
    published_at: "2026-07-20T10:00:00Z",
    created_at,
  },
];
