// Datos de ejemplo: se usan cuando Supabase no está configurado.
// Son los mismos que carga supabase/seed.sql.
import type {
  Club,
  ConfirmedPair,
  NewsArticle,
  Player,
  Tournament,
} from "@/types/models";

const created_at = "2026-09-01T12:00:00Z";

export const demoPlayers: Player[] = [
  {
    id: 1,
    slug: "martin-gomez",
    first_name: "Martín",
    last_name: "Gómez",
    photo_url: "/fotos/martin-gomez.jpg",
    city: "América",
    club: "Complejo El Remate",
    category: "6ta",
    gender: "masculino",
    side: "drive",
    ranking_points: 2480,
    matches_played: 38,
    matches_won: 29,
    titles: 4,
    bio: "Número uno del ranking regional. Drive agresivo, juega en pareja con Nicolás Ibarra desde 2024.",
    active: true,
    created_at,
  },
  {
    id: 2,
    slug: "lucas-ferreyra",
    first_name: "Lucas",
    last_name: "Ferreyra",
    photo_url: "/fotos/lucas-ferreyra.jpg",
    city: "Trenque Lauquen",
    club: "Pádel Norte",
    category: "6ta",
    gender: "masculino",
    side: "reves",
    ranking_points: 2315,
    matches_played: 35,
    matches_won: 25,
    titles: 3,
    bio: "Especialista en la bandeja y la víbora. Campeón del Clásico del Oeste 2026.",
    active: true,
    created_at,
  },
  {
    id: 3,
    slug: "tomas-aguirre",
    first_name: "Tomás",
    last_name: "Aguirre",
    photo_url: "/fotos/tomas-aguirre.jpg",
    city: "Pehuajó",
    club: "Bandeja Club",
    category: "7ma",
    gender: "masculino",
    side: "drive",
    ranking_points: 2140,
    matches_played: 33,
    matches_won: 22,
    titles: 2,
    bio: "La revelación de la temporada: subió de 8va a 7ma en un año.",
    active: true,
    created_at,
  },
  {
    id: 4,
    slug: "nicolas-ibarra",
    first_name: "Nicolás",
    last_name: "Ibarra",
    photo_url: "/fotos/nicolas-ibarra.jpg",
    city: "América",
    club: "Complejo El Remate",
    category: "7ma",
    gender: "masculino",
    side: "reves",
    ranking_points: 1985,
    matches_played: 30,
    matches_won: 19,
    titles: 1,
    bio: "Revés sólido y mucha lectura de juego. Compañero de Martín Gómez.",
    active: true,
    created_at,
  },
  {
    id: 5,
    slug: "franco-medina",
    first_name: "Franco",
    last_name: "Medina",
    photo_url: null,
    city: "General Villegas",
    club: "La Blindex",
    category: "8va",
    gender: "masculino",
    side: "drive",
    ranking_points: 1720,
    matches_played: 28,
    matches_won: 16,
    titles: 1,
    bio: "Fijo en todos los torneos del circuito desde hace tres temporadas.",
    active: true,
    created_at,
  },
  {
    id: 6,
    slug: "joaquin-sosa",
    first_name: "Joaquín",
    last_name: "Sosa",
    photo_url: null,
    city: "Salliqueló",
    club: "Pádel Oeste",
    category: "8va",
    gender: "masculino",
    side: "reves",
    ranking_points: 1590,
    matches_played: 26,
    matches_won: 14,
    titles: 0,
    bio: "Debutó en el circuito en 2025 y ya pelea los primeros puestos de 8va.",
    active: true,
    created_at,
  },
  {
    id: 7,
    slug: "camila-rodriguez",
    first_name: "Camila",
    last_name: "Rodríguez",
    photo_url: null,
    city: "América",
    club: "Bandeja Club",
    category: "6ta",
    gender: "femenino",
    side: "reves",
    ranking_points: 2390,
    matches_played: 36,
    matches_won: 28,
    titles: 5,
    bio: "Líder del ranking femenino con cinco títulos regionales.",
    active: true,
    created_at,
  },
  {
    id: 8,
    slug: "sofia-benitez",
    first_name: "Sofía",
    last_name: "Benítez",
    photo_url: null,
    city: "Trenque Lauquen",
    club: "Pádel Norte",
    category: "6ta",
    gender: "femenino",
    side: "drive",
    ranking_points: 2270,
    matches_played: 34,
    matches_won: 24,
    titles: 3,
    bio: "Drive potente y gran definición por arriba. Finalista de la Copa Aniversario.",
    active: true,
    created_at,
  },
  {
    id: 9,
    slug: "valentina-castro",
    first_name: "Valentina",
    last_name: "Castro",
    photo_url: null,
    city: "Pehuajó",
    club: "La Blindex",
    category: "7ma",
    gender: "femenino",
    side: "reves",
    ranking_points: 2050,
    matches_played: 31,
    matches_won: 21,
    titles: 2,
    bio: "Campeona de la Copa Aniversario 2026 junto a Florencia Molina.",
    active: true,
    created_at,
  },
  {
    id: 10,
    slug: "florencia-molina",
    first_name: "Florencia",
    last_name: "Molina",
    photo_url: null,
    city: "Carlos Tejedor",
    club: "Pádel Oeste",
    category: "7ma",
    gender: "femenino",
    side: "drive",
    ranking_points: 1890,
    matches_played: 29,
    matches_won: 18,
    titles: 1,
    bio: "Campeona de la Copa Aniversario 2026 y referente del pádel en Carlos Tejedor.",
    active: true,
    created_at,
  },
  {
    id: 11,
    slug: "julieta-paz",
    first_name: "Julieta",
    last_name: "Paz",
    photo_url: null,
    city: "América",
    club: "Complejo El Remate",
    category: "8va",
    gender: "femenino",
    side: "reves",
    ranking_points: 1705,
    matches_played: 27,
    matches_won: 15,
    titles: 1,
    bio: "Juega en América desde chica y es una de las promesas del circuito.",
    active: true,
    created_at,
  },
  {
    id: 12,
    slug: "agustina-rios",
    first_name: "Agustina",
    last_name: "Ríos",
    photo_url: null,
    city: "General Villegas",
    club: "Bandeja Club",
    category: "8va",
    gender: "femenino",
    side: "drive",
    ranking_points: 1560,
    matches_played: 25,
    matches_won: 13,
    titles: 0,
    bio: "Constancia pura: no se perdió ningún torneo de la temporada.",
    active: true,
    created_at,
  },
  {
    id: 13,
    slug: "ezequiel-navarro",
    first_name: "Ezequiel",
    last_name: "Navarro",
    photo_url: null,
    city: "América",
    club: "Complejo El Remate",
    category: "8va",
    gender: "masculino",
    side: "drive",
    ranking_points: 1480,
    matches_played: 24,
    matches_won: 12,
    titles: 0,
    bio: "Arrancó a jugar en 2026 y no se pierde una fecha del circuito.",
    active: true,
    created_at,
  },
  {
    id: 14,
    slug: "gaston-peralta",
    first_name: "Gastón",
    last_name: "Peralta",
    photo_url: null,
    city: "Trenque Lauquen",
    club: "Pádel Norte",
    category: "8va",
    gender: "masculino",
    side: "reves",
    ranking_points: 1345,
    matches_played: 22,
    matches_won: 11,
    titles: 0,
    bio: "Revés paciente. Juega siempre con Ezequiel Navarro.",
    active: true,
    created_at,
  },
  {
    id: 15,
    slug: "rodrigo-cabrera",
    first_name: "Rodrigo",
    last_name: "Cabrera",
    photo_url: null,
    city: "Pehuajó",
    club: "Bandeja Club",
    category: "8va",
    gender: "masculino",
    side: "drive",
    ranking_points: 1210,
    matches_played: 20,
    matches_won: 9,
    titles: 0,
    bio: "Viene del tenis y se está acostumbrando a jugar con las paredes.",
    active: true,
    created_at,
  },
  {
    id: 16,
    slug: "leandro-britos",
    first_name: "Leandro",
    last_name: "Britos",
    photo_url: null,
    city: "General Villegas",
    club: "La Blindex",
    category: "8va",
    gender: "masculino",
    side: "reves",
    ranking_points: 1075,
    matches_played: 18,
    matches_won: 7,
    titles: 0,
    bio: "El más regular de los que arrancaron este año en La Blindex.",
    active: true,
    created_at,
  },
  {
    id: 17,
    slug: "matias-olivera",
    first_name: "Matías",
    last_name: "Olivera",
    photo_url: null,
    city: "Salliqueló",
    club: "Pádel Oeste",
    category: "8va",
    gender: "masculino",
    side: "drive",
    ranking_points: 940,
    matches_played: 16,
    matches_won: 6,
    titles: 0,
    bio: "Debutó en el Abierto de Primavera y sumó sus primeros puntos.",
    active: true,
    created_at,
  },
  {
    id: 18,
    slug: "santiago-ferrari",
    first_name: "Santiago",
    last_name: "Ferrari",
    photo_url: null,
    city: "América",
    club: "Complejo El Remate",
    category: "8va",
    gender: "masculino",
    side: "reves",
    ranking_points: 820,
    matches_played: 14,
    matches_won: 4,
    titles: 0,
    bio: "Juega los martes a la noche y se anotó a su primer torneo.",
    active: true,
    created_at,
  },
  {
    id: 19,
    slug: "micaela-duarte",
    first_name: "Micaela",
    last_name: "Duarte",
    photo_url: null,
    city: "América",
    club: "Complejo El Remate",
    category: "8va",
    gender: "femenino",
    side: "drive",
    ranking_points: 1395,
    matches_played: 23,
    matches_won: 11,
    titles: 0,
    bio: "Empezó en la escuelita del club y ya juega todos los torneos.",
    active: true,
    created_at,
  },
  {
    id: 20,
    slug: "lucia-ferreyra",
    first_name: "Lucía",
    last_name: "Ferreyra",
    photo_url: null,
    city: "Trenque Lauquen",
    club: "Pádel Norte",
    category: "8va",
    gender: "femenino",
    side: "reves",
    ranking_points: 1150,
    matches_played: 19,
    matches_won: 8,
    titles: 0,
    bio: "Hermana de Lucas Ferreyra. Arrancó en 2026 y sube rápido.",
    active: true,
    created_at,
  },
  {
    id: 21,
    slug: "diego-sanchez",
    first_name: "Diego",
    last_name: "Sánchez",
    photo_url: null,
    city: "General Villegas",
    club: "La Blindex",
    category: "5ta",
    gender: "masculino",
    side: "drive",
    ranking_points: 2210,
    matches_played: 34,
    matches_won: 24,
    titles: 2,
    bio: "El de más experiencia del circuito: juega desde que abrió La Blindex.",
    active: true,
    created_at,
  },
  {
    id: 22,
    slug: "pablo-iriarte",
    first_name: "Pablo",
    last_name: "Iriarte",
    photo_url: null,
    city: "Pehuajó",
    club: "Bandeja Club",
    category: "5ta",
    gender: "masculino",
    side: "reves",
    ranking_points: 2035,
    matches_played: 31,
    matches_won: 21,
    titles: 1,
    bio: "Bandeja prolija y mucho oficio. Compañero de Diego Sánchez.",
    active: true,
    created_at,
  },
];

export const demoTournaments: Tournament[] = [
  {
    id: 1,
    slug: "abierto-de-primavera-2026",
    name: "Abierto de Primavera",
    description:
      "El torneo que abre la temporada de primavera en América. Tres días de pádel en las canchas del Complejo El Remate, con cuadros de 1ra y 2da masculino y puntos para el ranking regional.\n\nLas parejas se arman libremente. Cupo limitado a 24 parejas por categoría.",
    city: "América",
    venue: "Complejo El Remate",
    club_id: 1,
    starts_on: "2026-10-09",
    ends_on: "2026-10-11",
    category: "6ta y 7ma",
    gender: "masculino",
    status: "inscripciones",
    prize: "$1.500.000 en premios",
    champions: null,
    address: "América, Rivadavia, Buenos Aires",
    maps_url: null,
    capacity: 24,
    registration_opens_at: null,
    cover_url: null,
    featured: "principal",
    sponsor_name: null,
    category_min: 6,
    category_max: 7,
    category_sum: null,
    age_min: null,
    age_max: null,
    created_at,
  },
  {
    id: 2,
    slug: "copa-ciudad-de-trenque-lauquen-2026",
    name: "Copa Ciudad de Trenque Lauquen",
    description:
      "Torneo femenino de 3ra a 5ta categoría con fase de grupos y playoffs. Ideal para jugadoras que quieren sumar sus primeros puntos en el ranking.\n\nIncluye cena de camaradería el sábado a la noche.",
    city: "Trenque Lauquen",
    venue: "Pádel Norte",
    club_id: 2,
    starts_on: "2026-10-23",
    ends_on: "2026-10-25",
    category: "6ta a 8va",
    gender: "femenino",
    status: "inscripciones",
    prize: "Trofeos y $800.000 en premios",
    champions: null,
    address: "Trenque Lauquen, Buenos Aires",
    maps_url: null,
    capacity: 16,
    registration_opens_at: null,
    cover_url: null,
    featured: null,
    sponsor_name: null,
    category_min: 6,
    category_max: 8,
    category_sum: null,
    age_min: null,
    age_max: null,
    created_at,
  },
  {
    id: 3,
    slug: "torneo-mixto-nocturno-2026",
    name: "Torneo Mixto Nocturno",
    description:
      "Partidos de 20 a 2 h en la nueva cancha panorámica de Bandeja Club. Parejas mixtas, categoría suma 13.\n\nLas inscripciones abren el 20 de octubre.",
    city: "Pehuajó",
    venue: "Bandeja Club",
    club_id: 3,
    starts_on: "2026-11-13",
    ends_on: "2026-11-14",
    category: "Suma 13",
    gender: "mixto",
    status: "proximo",
    prize: null,
    champions: null,
    address: "Pehuajó, Buenos Aires",
    maps_url: null,
    capacity: 20,
    registration_opens_at: "2026-10-20T15:00:00.000Z",
    cover_url: null,
    featured: "sponsor",
    sponsor_name: "Bandeja Club",
    category_min: null,
    category_max: null,
    category_sum: 13,
    age_min: null,
    age_max: null,
    created_at,
  },
  {
    id: 4,
    slug: "master-de-fin-de-ano-2026",
    name: "Master de Fin de Año",
    description:
      "Los 8 mejores jugadores del ranking masculino se enfrentan en el cierre de la temporada. Formato round robin y final el domingo.\n\nEntrada libre y gratuita para el público.",
    city: "América",
    venue: "Complejo El Remate",
    club_id: 1,
    starts_on: "2026-12-11",
    ends_on: "2026-12-13",
    category: "Top 8 del ranking",
    gender: "masculino",
    status: "proximo",
    prize: "$3.000.000 en premios",
    champions: null,
    address: "América, Rivadavia, Buenos Aires",
    maps_url: null,
    capacity: null,
    registration_opens_at: null,
    cover_url: null,
    featured: null,
    sponsor_name: null,
    category_min: null,
    category_max: null,
    category_sum: null,
    age_min: null,
    age_max: null,
    created_at,
  },
  {
    id: 5,
    slug: "clasico-del-oeste-2026",
    name: "Clásico del Oeste",
    description:
      "El clásico de mitad de año, con parejas de toda la región en Carlos Tejedor.",
    city: "Carlos Tejedor",
    venue: "Polideportivo Municipal",
    club_id: null,
    starts_on: "2026-06-12",
    ends_on: "2026-06-14",
    category: "6ta",
    gender: "masculino",
    status: "finalizado",
    prize: null,
    champions: "Ferreyra / Aguirre",
    address: "Carlos Tejedor, Buenos Aires",
    maps_url: null,
    capacity: null,
    registration_opens_at: null,
    cover_url: null,
    featured: null,
    sponsor_name: null,
    category_min: 6,
    category_max: 6,
    category_sum: null,
    age_min: null,
    age_max: null,
    created_at,
  },
  {
    id: 6,
    slug: "invierno-padel-tour-2026",
    name: "Invierno Pádel Tour",
    description:
      "Fecha única del tour de invierno, con 20 parejas de 1ra categoría de toda la zona.",
    city: "General Villegas",
    venue: "La Blindex",
    club_id: null,
    starts_on: "2026-07-17",
    ends_on: "2026-07-19",
    category: "6ta",
    gender: "masculino",
    status: "finalizado",
    prize: null,
    champions: "Gómez / Ibarra",
    address: "General Villegas, Buenos Aires",
    maps_url: null,
    capacity: null,
    registration_opens_at: null,
    cover_url: null,
    featured: null,
    sponsor_name: null,
    category_min: 6,
    category_max: 6,
    category_sum: null,
    age_min: null,
    age_max: null,
    created_at,
  },
  {
    id: 7,
    slug: "copa-aniversario-padel-oeste-2026",
    name: "Copa Aniversario Pádel Oeste",
    description:
      "Torneo femenino por el aniversario de Pádel Oeste, con cuadros de 2da y 3ra.",
    city: "Salliqueló",
    venue: "Pádel Oeste",
    club_id: null,
    starts_on: "2026-08-14",
    ends_on: "2026-08-16",
    category: "7ma y 8va",
    gender: "femenino",
    status: "finalizado",
    prize: null,
    champions: "Castro / Molina",
    address: "Salliqueló, Buenos Aires",
    maps_url: null,
    capacity: null,
    registration_opens_at: null,
    cover_url: null,
    featured: null,
    sponsor_name: null,
    category_min: 7,
    category_max: 8,
    category_sum: null,
    age_min: null,
    age_max: null,
    created_at,
  },
];

/** Lugares ocupados de ejemplo (en Supabase salen de las inscripciones). */
export const demoSpots: Record<number, number> = { 1: 18, 2: 7 };

const author = "Redacción PaddleAmerica";

export const demoNews: NewsArticle[] = [
  {
    id: 1,
    slug: "inscripciones-abierto-de-primavera",
    title: "Abrieron las inscripciones para el Abierto de Primavera",
    excerpt:
      "Del 9 al 11 de octubre en el Complejo El Remate de América, con cuadros de 1ra y 2da masculino y $1.500.000 en premios.",
    body: "Ya están abiertas las inscripciones para el Abierto de Primavera, el torneo que da inicio a la segunda mitad de la temporada del circuito regional. Se jugará del 9 al 11 de octubre en las canchas del Complejo El Remate, en América.\n\nHabrá cuadros de 1ra y 2da categoría masculina, con un cupo de 24 parejas por categoría. El torneo reparte $1.500.000 en premios y suma puntos para el ranking regional.\n\nPara anotarte, creá tu cuenta en el sitio y completá la inscripción desde la página del torneo.",
    tag: "Torneos",
    author,
    cover_url: null,
    is_published: true,
    photos: [],
    published_at: "2026-09-10T15:00:00Z",
    created_at,
  },
  {
    id: 2,
    slug: "bandeja-club-estrena-cancha-panoramica",
    title: "Bandeja Club estrena cancha panorámica en Pehuajó",
    excerpt:
      "Es la primera cancha 100% de vidrio de la zona y va a ser sede del Torneo Mixto Nocturno.",
    body: "Bandeja Club inauguró su nueva cancha panorámica, la primera de la región con paredes completamente de vidrio y sin columnas en los laterales.\n\nLa cancha cuenta con iluminación LED y gradas para 120 personas, y será la sede del Torneo Mixto Nocturno de noviembre.",
    tag: "Clubes",
    author,
    cover_url: null,
    is_published: true,
    photos: [],
    published_at: "2026-09-05T13:00:00Z",
    created_at,
  },
  {
    id: 3,
    slug: "ranking-despues-de-agosto",
    title: "Así quedó el ranking regional después de agosto",
    excerpt:
      "Martín Gómez y Camila Rodríguez siguen al frente. Tomás Aguirre, la gran sorpresa del mes.",
    body: "Con los puntos de la Copa Aniversario ya sumados, se actualizó el ranking regional. Martín Gómez sigue siendo el número uno en masculino y Camila Rodríguez lidera el femenino por segundo mes consecutivo.\n\nEl gran salto lo dio Tomás Aguirre, que tras ganar el Clásico del Oeste junto a Lucas Ferreyra ya es tercero en el ranking masculino.\n\nEl próximo movimiento llegará después del Abierto de Primavera, en octubre.",
    tag: "Ranking",
    author,
    cover_url: null,
    is_published: true,
    photos: [],
    published_at: "2026-09-01T12:00:00Z",
    created_at,
  },
  {
    id: 4,
    slug: "castro-molina-campeonas-copa-aniversario",
    title: "Castro y Molina, campeonas de la Copa Aniversario",
    excerpt:
      "Vencieron en la final a Rodríguez y Benítez en un partido que se definió en el tercer set.",
    body: "Valentina Castro y Florencia Molina se quedaron con la Copa Aniversario de Pádel Oeste tras vencer en la final a Camila Rodríguez y Sofía Benítez por 6-4, 3-6 y 7-5.\n\nFue el primer título de la temporada para la pareja, que venía de perder dos semifinales seguidas. Con este resultado, ambas suben posiciones en el ranking femenino.",
    tag: "Torneos",
    author,
    cover_url: null,
    is_published: true,
    photos: [],
    published_at: "2026-08-17T10:00:00Z",
    created_at,
  },
  {
    id: 5,
    slug: "gomez-ibarra-campeones-invierno-padel-tour",
    title: "Gómez e Ibarra ganaron el Invierno Pádel Tour",
    excerpt:
      "La pareja de América no perdió ningún set en todo el torneo disputado en General Villegas.",
    body: "Martín Gómez y Nicolás Ibarra fueron los campeones del Invierno Pádel Tour, que reunió a 20 parejas de 1ra categoría en las canchas de La Blindex, en General Villegas.\n\nEn la final superaron a Lucas Ferreyra y Tomás Aguirre por 6-3 y 6-2, cerrando un torneo en el que no cedieron ningún set.",
    tag: "Torneos",
    author,
    cover_url: null,
    is_published: true,
    photos: [],
    published_at: "2026-07-20T10:00:00Z",
    created_at,
  },
];

export const demoClubs: Club[] = [
  {
    id: 1,
    slug: "complejo-el-remate",
    name: "Complejo El Remate",
    city: "América",
    address: "América, Rivadavia, Buenos Aires",
    maps_url: null,
    description:
      "El complejo más grande de América: canchas de blindex techadas, vestuarios y buffet. Sede del Abierto de Primavera y del Masters de fin de año.",
    courts: 4,
    phone: null,
    instagram: null,
    cover_url: null,
    created_at,
  },
  {
    id: 2,
    slug: "padel-norte",
    name: "Pádel Norte",
    city: "Trenque Lauquen",
    address: null,
    maps_url: null,
    description:
      "Tres canchas de césped sintético en la zona norte de Trenque Lauquen.",
    courts: 3,
    phone: null,
    instagram: null,
    cover_url: null,
    created_at,
  },
  {
    id: 3,
    slug: "bandeja-club",
    name: "Bandeja Club",
    city: "Pehuajó",
    address: null,
    maps_url: null,
    description: null,
    courts: 2,
    phone: null,
    instagram: null,
    cover_url: null,
    created_at,
  },
];

/** Parejas confirmadas de ejemplo, por torneo. */
export const demoConfirmedPairs: Record<number, ConfirmedPair[]> = {
  1: [
    {
      id: 1,
      player: { name: "Martín Gómez", avatarUrl: null, slug: "martin-gomez" },
      partner: {
        name: "Nicolás Ibarra",
        avatarUrl: null,
        slug: "nicolas-ibarra",
      },
    },
    {
      id: 2,
      player: { name: "Tomás Aguirre", avatarUrl: null, slug: "tomas-aguirre" },
      partner: {
        name: "Lucas Ferreyra",
        avatarUrl: null,
        slug: "lucas-ferreyra",
      },
    },
  ],
};
